# Generated by Django 5.1.15 on 2025-12-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
    ]
