# Generated by Django 5.1.7 on 2025-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact_list',
        ),
    ]
