# Generated by Django 5.2.9 on 2025-12-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_options"),
        ("crm", "0008_remove_legal_company_remove_person_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts",
                to="crm.company",
                verbose_name="Компании",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.JSONField(blank=True, default=list, verbose_name="Эл. почта"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.JSONField(blank=True, default=list, verbose_name="Телефон"),
        ),
    ]
