# Generated by Django 5.1.7 on 2025-04-06 00:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('isGroup', models.BooleanField(default=False, verbose_name='Группа')),
                ('company_type', models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], max_length=10, verbose_name='Тип контрагента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inCharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.company', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'crm_companies',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ОГРН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ОГРН')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='crm.company')),
            ],
            options={
                'verbose_name': 'Профиль ИП',
                'verbose_name_plural': 'Профили ИП',
                'db_table': 'crm_business_individuals',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='КПП должен содержать только цифры', regex='^[0-9]*$')], verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ОГРН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ОГРН')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='crm.company')),
            ],
            options={
                'verbose_name': 'Профиль юр. лица',
                'verbose_name_plural': 'Профили юр. лиц',
                'db_table': 'crm_business_legals',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('personal_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Удостоверение личности')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='crm.company')),
            ],
            options={
                'verbose_name': 'Профиль физ. лица',
                'verbose_name_plural': 'Профили физ. лиц',
                'db_table': 'crm_business_persons',
            },
        ),
    ]
