# Generated by Django 5.1.8 on 2025-04-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='inCharge',
            new_name='in_charge',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='isGroup',
            new_name='is_group',
        ),
        migrations.AlterField(
            model_name='individual',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='crm.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legal',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='crm.company'),
            preserve_default=False,
        ),
    ]
