# Generated by Django 4.2.5 on 2023-09-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='crm_users',
        ),
    ]
