# Generated by Django 5.1.8 on 2025-04-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_incharge_company_in_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], max_length=10, null=True, verbose_name='Тип контрагента'),
        ),
    ]
