# Generated by Django 5.1.15 on 2025-12-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_company_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="individual",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual",
                to="crm.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="legal",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal",
                to="crm.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person",
                to="crm.company",
                verbose_name="Компания",
            ),
        ),
        migrations.CreateModel(
            name="GaplessSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "user_initials",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("value", models.BigIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "tenant", "year", "user_initials"],
                        name="crm_gapless_name_df65be_idx",
                    )
                ],
                "unique_together": {("name", "tenant", "year", "user_initials")},
            },
        ),
    ]
