# Generated by Django 5.2.7 on 2025-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_company_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaplessSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('user_initials', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'tenant', 'year', 'user_initials'], name='crm_gapless_name_df65be_idx')],
                'unique_together': {('name', 'tenant', 'year', 'user_initials')},
            },
        ),
    ]
