# Generated by Django 5.1.15 on 2025-12-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_company_created_at_alter_company_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gaplesssequence",
            options={"verbose_name": "Нумератор", "verbose_name_plural": "Нумераторы"},
        ),
        migrations.AlterField(
            model_name="gaplesssequence",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Имя последовательности"
            ),
        ),
        migrations.AlterField(
            model_name="gaplesssequence",
            name="tenant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тенант"
            ),
        ),
        migrations.AlterField(
            model_name="gaplesssequence",
            name="user_initials",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Инициалы пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="gaplesssequence",
            name="value",
            field=models.BigIntegerField(default=0, verbose_name="Текущее значение"),
        ),
        migrations.AlterField(
            model_name="gaplesssequence",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Год"),
        ),
    ]
