# Generated by Django 4.2.5 on 2023-09-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='typeOfBusiness',
            new_name='_typeOfBusiness',
        ),
    ]
