# Generated by Django 4.2.5 on 2023-10-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0005_rename_typeofbusiness_company__typeofbusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn_ip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'crm_Business_individuals',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'crm_Business_legals',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'crm_Business_persons',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='_typeOfBusiness',
            field=models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], default='Legal', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='company',
            table='crm_companies',
        ),
    ]
