# Generated by Django 5.2.7 on 2025-12-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_gaplesssequence'),
        ('crm', '0005_alter_gaplesssequence_options_and_more'),
    ]

    operations = [
    ]
