# Generated by Django 5.2.7 on 2025-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_merge_20251204_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaplesssequence',
            options={'verbose_name': 'Нумератор', 'verbose_name_plural': 'Нумераторы'},
        ),
        migrations.AlterField(
            model_name='gaplesssequence',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя последовательности'),
        ),
        migrations.AlterField(
            model_name='gaplesssequence',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='gaplesssequence',
            name='user_initials',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инициалы пользователя'),
        ),
        migrations.AlterField(
            model_name='gaplesssequence',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='Текущее значение'),
        ),
        migrations.AlterField(
            model_name='gaplesssequence',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
