# Generated by Django 4.2.5 on 2023-10-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_individual_legal_person_company_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='ogrn_ip',
            new_name='ogrn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='_typeOfBusiness',
        ),
        migrations.RemoveField(
            model_name='company',
            name='full_name',
        ),
        migrations.AddField(
            model_name='company',
            name='typeOfBusiness',
            field=models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legal',
            name='formal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='individual',
            table='crm_business_individuals',
        ),
        migrations.AlterModelTable(
            name='legal',
            table='crm_business_legals',
        ),
        migrations.AlterModelTable(
            name='person',
            table='crm_business_persons',
        ),
    ]
