# Generated by Django 4.2.5 on 2023-11-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_ogrn_ip_individual_ogrn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.individual',),
        ),
        migrations.CreateModel(
            name='LegalProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.legal',),
        ),
        migrations.CreateModel(
            name='PersonProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.person',),
        ),
    ]
