# Generated by Django 5.2.9 on 2025-12-05 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_alter_gaplesssequence_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legal",
            name="company",
        ),
        migrations.RemoveField(
            model_name="person",
            name="company",
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="company",
            name="formal_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Полное наименование"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="inn",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_digits",
                        message="ИНН должен содержать только цифры",
                        regex="^[0-9]*$",
                    )
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="kpp",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_digits",
                        message="КПП должен содержать только цифры",
                        regex="^[0-9]*$",
                    )
                ],
                verbose_name="КПП",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="mail_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Почтовый адрес"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="ogrn",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_digits",
                        message="ОГРН должен содержать только цифры",
                        regex="^[0-9]*$",
                    )
                ],
                verbose_name="ОГРН",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="personal_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Удостоверение личности",
            ),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность"
                    ),
                ),
                (
                    "authority_doc",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Документ полномочий"
                    ),
                ),
                (
                    "details",
                    models.CharField(blank=True, max_length=255, verbose_name="Детали"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="crm.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Представитель",
                "verbose_name_plural": "Представители",
                "db_table": "crm_agents",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="representative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="representative_companies",
                to="crm.agent",
                verbose_name="Представитель",
            ),
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100, verbose_name="Номер")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="crm.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
                "db_table": "crm_agreements",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="main_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_agreement_companies",
                to="crm.agreement",
                verbose_name="Основной договор",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=100, verbose_name="Номер счета"),
                ),
                ("bank", models.CharField(max_length=255, verbose_name="Банк")),
                ("bik", models.CharField(max_length=50, verbose_name="БИК")),
                (
                    "cor_number",
                    models.CharField(max_length=100, verbose_name="Корр. счет"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="crm.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковский счет",
                "verbose_name_plural": "Банковские счета",
                "db_table": "crm_bank_accounts",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="main_bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_account_companies",
                to="crm.bankaccount",
                verbose_name="Основной счет",
            ),
        ),
        migrations.DeleteModel(
            name="Individual",
        ),
        migrations.DeleteModel(
            name="Legal",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
