# Generated by Django 4.2.5 on 2023-11-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_individualproxy_legalproxy_personproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualProxy',
        ),
        migrations.DeleteModel(
            name='LegalProxy',
        ),
        migrations.DeleteModel(
            name='PersonProxy',
        ),
    ]
