# Generated by Django 4.2.5 on 2023-11-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_individual_full_name_individual_inn_individual_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='full_name',
            new_name='formal_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='formal_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='name',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
