# Generated by Django 4.2.5 on 2023-11-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_individual_partner_legal_partner_person_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='object_id',
        ),
    ]
