# Generated by Django 4.2.5 on 2023-11-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_company_content_type_remove_company_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='crm.company'),
        ),
    ]
