# Generated by Django 4.2.5 on 2023-11-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_individual_partner_alter_legal_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='crm.company'),
        ),
    ]
