# Generated by Django 4.2.5 on 2023-11-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_person_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='inn',
        ),
    ]
