# Generated by Django 4.2.5 on 2023-11-07 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_company_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='in_charge',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_group',
        ),
        migrations.AddField(
            model_name='company',
            name='inCharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='company',
            name='isGroup',
            field=models.BooleanField(default=False, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='company',
            name='typeOfBusiness',
            field=models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], max_length=10, verbose_name='Тип контрагента'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='formal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='formal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='formal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_id',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Удостоверение личности'),
        ),
    ]
