# Generated by Django 4.2.5 on 2024-03-12 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_company_in_charge_remove_company_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.company', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='company',
            name='typeOfBusiness',
            field=models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], max_length=10, null=True, verbose_name='Тип контрагента'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ОГРН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='КПП должен содержать только цифры', regex='^[0-9]*$')], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ОГРН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН'),
        ),
    ]
