# Generated by Django 5.1.7 on 2025-03-31 02:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_company_parent_alter_company_typeofbusiness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Профиль ИП', 'verbose_name_plural': 'Профили ИП'},
        ),
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'Профиль юр. лица', 'verbose_name_plural': 'Профили юр. лиц'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Профиль физ. лица', 'verbose_name_plural': 'Профили физ. лиц'},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='partner',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='partner',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='partner',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='typeOfBusiness',
        ),
        migrations.RemoveField(
            model_name='person',
            name='inn',
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('Legal', 'Юридическое лицо'), ('Individual', 'Индивидуальный предприниматель'), ('Person', 'Физическое лицо'), ('Government', 'Государственный орган'), ('Other', 'Другой')], default='Legal', max_length=10, verbose_name='Тип контрагента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='inn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_digits', message='ИНН должен содержать только цифры', regex='^[0-9]*$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Удостоверение личности'),
        ),
    ]
