# Generated by Django 4.2.5 on 2025-03-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique_for_year='date_open', verbose_name='Номер')),
                ('date_open', models.DateField(verbose_name='Дата')),
                ('is_open', models.BooleanField(default=True, verbose_name='Действующий')),
                ('odometer_start', models.PositiveSmallIntegerField(verbose_name='Показание одометра перед выездом')),
                ('odometer_end', models.PositiveSmallIntegerField(verbose_name='Показание одометра после возвращения')),
                ('date_close', models.DateField(blank=True, verbose_name='Дата закрытия')),
            ],
        ),
        migrations.RemoveField(
            model_name='truckassignment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='truckassignment',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='truckassignment',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='single',
        ),
        migrations.AddField(
            model_name='driver',
            name='data_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквизиты документа'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='driver',
            name='type_id',
            field=models.CharField(blank=True, choices=[('Passport', 'Паспорт'), ('PersonalID', 'Удостоверение личности')], max_length=55, null=True, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='truck',
            name='brand',
            field=models.CharField(max_length=30, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='truck',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='truck',
            name='type_truck',
            field=models.CharField(choices=[('DryVan', 'Тентованный'), ('Reefer', 'Рефрижиратор'), ('SideWall', 'Бортовой'), ('DoubleVan', 'Сцепка'), ('FlatBed', 'Трал'), ('Platform', 'Площадка'), ('LowBed', 'Низкорамный')], max_length=55, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_licence',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Водительское удостоверение'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration',
            field=models.CharField(max_length=50, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='TruckAssignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.truck', verbose_name='Автомобиль'),
        ),
    ]
