# Generated by Django 5.1.15 on 2025-12-04 05:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=55, verbose_name="Номер")),
                ("date", models.DateField(verbose_name="Дата")),
                ("route", models.CharField(max_length=255, verbose_name="Маргрут")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ставка",
                    ),
                ),
                (
                    "payment",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "с НДС"),
                            (2, "без НДС"),
                            (3, "Наличные"),
                            (4, "Прочее"),
                        ],
                        default=1,
                        verbose_name="Форма оплаты",
                    ),
                ),
                (
                    "settlement",
                    models.CharField(max_length=255, verbose_name="Порядок оплаты"),
                ),
                ("dateBegin", models.DateField(verbose_name="Дата погрузки")),
                ("dateEnds", models.DateField(verbose_name="Дата выгрузки")),
                (
                    "contact_tmp",
                    models.CharField(
                        default="", max_length=255, verbose_name="Контакты по заявке"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "verbose_name": "Путевой лист",
                "verbose_name_plural": "Путевые листы",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Водитель", "verbose_name_plural": "Водители"},
        ),
        migrations.AlterModelOptions(
            name="truck",
            options={"verbose_name": "Автомобиль", "verbose_name_plural": "Автомобили"},
        ),
    ]
