# Generated by Django 4.2.5 on 2025-03-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_assignment_remove_truckassignment_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='type_id',
            field=models.CharField(blank=True, choices=[('Passport', 'Паспорт'), ('PersonalID', 'Удостоверение личности')], default='Passport', max_length=55, null=True, verbose_name='Документ'),
        ),
    ]
