# Generated by Django 5.1.7 on 2025-03-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_alter_driver_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='odometer_end',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Показание одометра после возвращения'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='odometer_start',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Показание одометра перед выездом'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='data_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквизиты'),
        ),
    ]
